-- V12__expand_catalog.sql
-- Soft-delete stray test products created through an ad-hoc admin API test,
-- and expand the catalog from 4 to 8 real products per category.

UPDATE products SET is_deleted = true, is_active = false, deleted_date = now()
WHERE ornament_id IN ('ORN-000021', 'ORN-000022');

INSERT INTO products (
    ornament_id, name, slug, short_description, description, base_price, discounted_price,
    metal_type, weight_grams, category_id, sub_category_id, is_active, is_featured, stock_status,
    meta_title, meta_description, created_by, updated_by
) VALUES
    ('ORN-000023', 'Layered Pearl Necklace', 'layered-pearl-necklace', 'Multi-strand pearl necklace with gold accents.', 'A graceful multi-strand necklace pairing freshwater-style pearls with delicate gold-plated chain links.', 5200.00, NULL, 'SILVER', 34.00, (SELECT id FROM categories WHERE slug = 'necklaces'), (SELECT id FROM sub_categories WHERE slug = 'long-chains'), true, false, 'IN_STOCK', 'Layered Pearl Necklace | Sri Sai Fashion Jewellery', 'Multi-strand pearl necklace with gold-plated accents.', 'system', 'system'),
    ('ORN-000024', 'Baroque Pearl Statement Necklace', 'baroque-pearl-statement-necklace', 'Bold baroque pearl choker with gold chain.', 'A statement choker featuring irregular baroque-style pearls set along a warm gold-plated chain.', 6900.00, 5800.00, 'GOLD_PLATED', 40.00, (SELECT id FROM categories WHERE slug = 'necklaces'), (SELECT id FROM sub_categories WHERE slug = 'chokers-necklaces'), true, true, 'IN_STOCK', 'Baroque Pearl Statement Necklace | Sri Sai Fashion Jewellery', 'Bold baroque pearl statement choker necklace.', 'system', 'system'),
    ('ORN-000025', 'Dual Chain Pendant Necklace', 'dual-chain-pendant-necklace', 'Layered dual-chain necklace with pendant.', 'Two fine chains of differing lengths, each finished with a subtle pendant, designed to be worn together or alone.', 4500.00, NULL, 'ROSE_GOLD_PLATED', 28.00, (SELECT id FROM categories WHERE slug = 'necklaces'), (SELECT id FROM sub_categories WHERE slug = 'long-chains'), true, false, 'IN_STOCK', 'Dual Chain Pendant Necklace | Sri Sai Fashion Jewellery', 'Layered dual-chain pendant necklace in rose gold finish.', 'system', 'system'),
    ('ORN-000026', 'Gold Pearl Drop Pendant', 'gold-pearl-drop-pendant', 'Delicate pendant necklace with pearl drop.', 'A fine gold-plated chain finished with a single elegant pearl-drop pendant for everyday wear.', 3900.00, 3300.00, 'GOLD_PLATED', 22.00, (SELECT id FROM categories WHERE slug = 'necklaces'), (SELECT id FROM sub_categories WHERE slug = 'chokers-necklaces'), true, false, 'IN_STOCK', 'Gold Pearl Drop Pendant | Sri Sai Fashion Jewellery', 'Delicate gold-plated pearl drop pendant necklace.', 'system', 'system'),

    ('ORN-000027', 'Vintage Drop Earrings', 'vintage-drop-earrings', 'Oxidized vintage-style drop earrings.', 'Intricately detailed drop earrings finished in an oxidized silver tone for a vintage, heirloom look.', 2400.00, NULL, 'OXIDIZED', 11.00, (SELECT id FROM categories WHERE slug = 'earrings'), (SELECT id FROM sub_categories WHERE slug = 'jhumkas'), true, false, 'IN_STOCK', 'Vintage Drop Earrings | Sri Sai Fashion Jewellery', 'Oxidized vintage-style drop earrings.', 'system', 'system'),
    ('ORN-000028', 'Traditional Gold Danglers', 'traditional-gold-danglers', 'Classic gold-plated dangler earrings.', 'Traditional dangler earrings finished in warm imitation gold, light enough for all-day wear.', 2900.00, 2500.00, 'GOLD_PLATED', 13.00, (SELECT id FROM categories WHERE slug = 'earrings'), (SELECT id FROM sub_categories WHERE slug = 'jhumkas'), true, true, 'IN_STOCK', 'Traditional Gold Danglers | Sri Sai Fashion Jewellery', 'Classic gold-plated traditional dangler earrings.', 'system', 'system'),
    ('ORN-000029', 'Emerald Stud Earrings', 'emerald-stud-earrings', 'Gold-plated studs with emerald-green stone.', 'Petite stud earrings set with a faceted emerald-green stone, finished in imitation gold.', 1700.00, NULL, 'GOLD_PLATED', 5.50, (SELECT id FROM categories WHERE slug = 'earrings'), (SELECT id FROM sub_categories WHERE slug = 'studs'), true, false, 'IN_STOCK', 'Emerald Stud Earrings | Sri Sai Fashion Jewellery', 'Gold-plated stud earrings with emerald-green stone.', 'system', 'system'),
    ('ORN-000030', 'Heart Diamond Stud Earrings', 'heart-diamond-stud-earrings', 'Heart-shaped CZ stud earrings.', 'Sweet heart-shaped stud earrings set with sparkling cubic zirconia stones.', 2100.00, 1850.00, 'CZ', 4.20, (SELECT id FROM categories WHERE slug = 'earrings'), (SELECT id FROM sub_categories WHERE slug = 'studs'), true, false, 'IN_STOCK', 'Heart Diamond Stud Earrings | Sri Sai Fashion Jewellery', 'Heart-shaped cubic zirconia stud earrings.', 'system', 'system'),

    ('ORN-000031', 'Polished Gold Bangle Pair', 'polished-gold-bangle-pair', 'Pair of high-shine gold-plated bangles.', 'A pair of smooth, high-polish bangles in a warm imitation-gold finish, designed to be worn together.', 4800.00, NULL, 'GOLD_PLATED', 42.00, (SELECT id FROM categories WHERE slug = 'bangles'), (SELECT id FROM sub_categories WHERE slug = 'kada'), true, false, 'IN_STOCK', 'Polished Gold Bangle Pair | Sri Sai Fashion Jewellery', 'Pair of high-shine gold-plated bangles.', 'system', 'system'),
    ('ORN-000032', 'Classic Stackable Bangle Set', 'classic-stackable-bangle-set', 'Set of slim stackable bangles.', 'A set of slim, stackable bangles finished in imitation gold, designed to be worn in multiples.', 3600.00, 3100.00, 'GOLD_PLATED', 30.00, (SELECT id FROM categories WHERE slug = 'bangles'), (SELECT id FROM sub_categories WHERE slug = 'charm-bangles'), true, true, 'IN_STOCK', 'Classic Stackable Bangle Set | Sri Sai Fashion Jewellery', 'Set of slim stackable gold-plated bangles.', 'system', 'system'),
    ('ORN-000033', 'Turquoise Charm Bangle', 'turquoise-charm-bangle', 'Silver-finish bangle with turquoise beads.', 'A silver-tone bangle accented with turquoise-hued beads for a pop of colour.', 2200.00, NULL, 'SILVER', 20.00, (SELECT id FROM categories WHERE slug = 'bangles'), (SELECT id FROM sub_categories WHERE slug = 'charm-bangles'), true, false, 'IN_STOCK', 'Turquoise Charm Bangle | Sri Sai Fashion Jewellery', 'Silver-finish bangle with turquoise bead accents.', 'system', 'system'),
    ('ORN-000034', 'Beaded Stretch Bangle Stack', 'beaded-stretch-bangle-stack', 'Set of beaded stretch bangles.', 'A stretchable stack of beaded bangles in a warm brass tone, easy to layer with other pieces.', 1600.00, NULL, 'BRASS', 15.00, (SELECT id FROM categories WHERE slug = 'bangles'), (SELECT id FROM sub_categories WHERE slug = 'charm-bangles'), true, false, 'IN_STOCK', 'Beaded Stretch Bangle Stack | Sri Sai Fashion Jewellery', 'Set of beaded stretch bangles in brass tone.', 'system', 'system'),

    ('ORN-000035', 'Diamond Halo Statement Ring', 'diamond-halo-statement-ring', 'CZ halo statement ring.', 'A striking statement ring featuring a halo of cubic zirconia stones around a central solitaire.', 3200.00, 2700.00, 'CZ', 6.50, (SELECT id FROM categories WHERE slug = 'rings'), (SELECT id FROM sub_categories WHERE slug = 'cocktail-rings'), true, true, 'IN_STOCK', 'Diamond Halo Statement Ring | Sri Sai Fashion Jewellery', 'Cubic zirconia halo statement ring.', 'system', 'system'),
    ('ORN-000036', 'Emerald Cocktail Ring', 'emerald-cocktail-ring', 'Gold-plated ring with emerald-green stone.', 'A bold cocktail ring set with a large emerald-green stone, finished in imitation gold.', 3800.00, NULL, 'GOLD_PLATED', 8.00, (SELECT id FROM categories WHERE slug = 'rings'), (SELECT id FROM sub_categories WHERE slug = 'cocktail-rings'), true, false, 'IN_STOCK', 'Emerald Cocktail Ring | Sri Sai Fashion Jewellery', 'Gold-plated cocktail ring with emerald-green stone.', 'system', 'system'),
    ('ORN-000037', 'Classic Gold Band', 'classic-gold-band', 'Simple everyday gold-plated band.', 'A clean, simple band ring in a warm imitation-gold finish, suited to everyday wear or stacking.', 1900.00, NULL, 'GOLD_PLATED', 4.50, (SELECT id FROM categories WHERE slug = 'rings'), (SELECT id FROM sub_categories WHERE slug = 'bands'), true, false, 'IN_STOCK', 'Classic Gold Band | Sri Sai Fashion Jewellery', 'Simple everyday gold-plated band ring.', 'system', 'system'),
    ('ORN-000038', 'Stackable Ring Set', 'stackable-ring-set', 'Set of three slim stacking rings.', 'A set of three slim rings in a rose-gold-plated finish, designed to be worn stacked or separately.', 2300.00, 1950.00, 'ROSE_GOLD_PLATED', 6.00, (SELECT id FROM categories WHERE slug = 'rings'), (SELECT id FROM sub_categories WHERE slug = 'bands'), true, false, 'IN_STOCK', 'Stackable Ring Set | Sri Sai Fashion Jewellery', 'Set of three slim rose-gold-plated stacking rings.', 'system', 'system'),

    ('ORN-000039', 'Antique Gold Bridal Set', 'antique-gold-bridal-set', 'Complete antique-finish bridal necklace set.', 'A complete bridal necklace and earring set finished in an antique-gold plating for a heritage look.', 16500.00, 14200.00, 'GOLD_PLATED', 105.00, (SELECT id FROM categories WHERE slug = 'bridal-sets'), (SELECT id FROM sub_categories WHERE slug = 'necklace-sets'), true, true, 'IN_STOCK', 'Antique Gold Bridal Set | Sri Sai Fashion Jewellery', 'Complete antique-finish gold bridal necklace set.', 'system', 'system'),
    ('ORN-000040', 'Kundan Bridal Choker Set', 'kundan-bridal-choker-set', 'Kundan choker and earring bridal set.', 'A regal kundan choker paired with matching earrings, finished in a 22k-look imitation gold plating.', 13800.00, NULL, 'GOLD_PLATED', 88.00, (SELECT id FROM categories WHERE slug = 'bridal-sets'), (SELECT id FROM sub_categories WHERE slug = 'necklace-sets'), true, false, 'IN_STOCK', 'Kundan Bridal Choker Set | Sri Sai Fashion Jewellery', 'Kundan choker and earring bridal set.', 'system', 'system'),
    ('ORN-000041', 'Ruby Maang Tikka Set', 'ruby-maang-tikka-set', 'Ruby-accented maang tikka with earrings.', 'A matching maang tikka and earring set with ruby-red stone accents, finished in imitation gold.', 10200.00, 8700.00, 'GOLD_PLATED', 50.00, (SELECT id FROM categories WHERE slug = 'bridal-sets'), (SELECT id FROM sub_categories WHERE slug = 'maang-tikka-sets'), true, true, 'IN_STOCK', 'Ruby Maang Tikka Set | Sri Sai Fashion Jewellery', 'Ruby-accented maang tikka and earring bridal set.', 'system', 'system'),
    ('ORN-000042', 'Polki Maang Tikka Duo', 'polki-maang-tikka-duo', 'Polki-style maang tikka and earring duo.', 'A polki-inspired maang tikka and earring duo set with sparkling cubic zirconia work.', 11500.00, NULL, 'CZ', 55.00, (SELECT id FROM categories WHERE slug = 'bridal-sets'), (SELECT id FROM sub_categories WHERE slug = 'maang-tikka-sets'), true, false, 'IN_STOCK', 'Polki Maang Tikka Duo | Sri Sai Fashion Jewellery', 'Polki-style maang tikka and earring duo bridal set.', 'system', 'system');

INSERT INTO product_images (product_id, image_url, alt_text, display_order, is_primary, created_by, updated_by)
SELECT p.id, v.image_url, p.name, 0, true, 'system', 'system'
FROM products p
JOIN (VALUES
    ('ORN-000023', '/images/products/necklaces/layered-pearl-necklace.jpg'),
    ('ORN-000024', '/images/products/necklaces/baroque-pearl-statement-necklace.jpg'),
    ('ORN-000025', '/images/products/necklaces/dual-chain-pendant-necklace.jpg'),
    ('ORN-000026', '/images/products/necklaces/gold-pearl-drop-pendant.jpg'),
    ('ORN-000027', '/images/products/earrings/vintage-drop-earrings.jpg'),
    ('ORN-000028', '/images/products/earrings/traditional-gold-danglers.jpg'),
    ('ORN-000029', '/images/products/earrings/emerald-stud-earrings.jpg'),
    ('ORN-000030', '/images/products/earrings/heart-diamond-stud-earrings.jpg'),
    ('ORN-000031', '/images/products/bangles/polished-gold-bangle-pair.jpg'),
    ('ORN-000032', '/images/products/bangles/classic-stackable-bangle-set.jpg'),
    ('ORN-000033', '/images/products/bangles/turquoise-charm-bangle.jpg'),
    ('ORN-000034', '/images/products/bangles/beaded-stretch-bangle-stack.jpg'),
    ('ORN-000035', '/images/products/rings/diamond-halo-statement-ring.jpg'),
    ('ORN-000036', '/images/products/rings/emerald-cocktail-ring.jpg'),
    ('ORN-000037', '/images/products/rings/classic-gold-band.jpg'),
    ('ORN-000038', '/images/products/rings/stackable-ring-set.jpg'),
    ('ORN-000039', '/images/products/bridal-sets/antique-gold-bridal-set.jpg'),
    ('ORN-000040', '/images/products/bridal-sets/kundan-bridal-choker-set.jpg'),
    ('ORN-000041', '/images/products/bridal-sets/ruby-maang-tikka-set.jpg'),
    ('ORN-000042', '/images/products/bridal-sets/polki-maang-tikka-duo.jpg')
) AS v(ornament_id, image_url) ON v.ornament_id = p.ornament_id;
